package com.limasoftware.Safety.enums;

public enum SchedulingType {
    CONSULTA_CLINICA_GERAL,
    CONSULTA_PEDIATRIA,
    CONSULTA_CARDIOLOGIA,
    CONSULTA_DERMATOLOGIA,
    CONSULTA_GINECOLOGIA,
    CONSULTA_ORTOPEDIA,
    CONSULTA_NEUROLOGIA,

    RETORNO_MEDICO,
    TELEMEDICINA,
    EXAME_LABORATORIAL,
    EXAME_IMAGEM,
    PROCEDIMENTO_SIMPLIFICADO
}
